[package]
name = "real-number-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# this crate is used by rational number
fraction-rs = { git = "https://github.com/haruki7049/fraction-rs.git" }
